### ISSUE TITLE
Audio engine breaks world events in Safari

### ISSUE THREAD

**Issue by Continuities** [orsi/adarkroom#24]
For some reason, loading the music for locations in the worldmap fails in Safari. This causes an exception in the code that stops location background music, resulting in the player unable to leave a location.

**Comment by orsi** [comment]
Fixed in 9d8049988d47432e31d1da2db585117bb4456c1b.

Safari's Web Audio API doesn't return a promise when using decodeAudioData(), which leads to a bunch of chain events that eventually break when trying to stop() a null audio buffer source :P. I looked into using a [web audio polyfill](https://github.com/chrisguttandin/standardized-audio-context) to bridge the gap between each browser's implementation, but figured it was overkill for one feature. I opted to make a simple solution, and it works.
