### ISSUE TITLE
Optimize audio bandwidth requirements

### ISSUE THREAD

**Issue by Continuities** [orsi/adarkroom#25]
Everything encoded in FLAC, as well as loading audio assets even when sound is disabled is pretty expensive from a bandwidth perspective. As it is, it's too expensive for doublespeak to host on the official site. That's a serious bummer, because I love the audio.

**Comment by orsi** [comment]
Will work on compressing the audio further, as well as lazy loading audio only when sound is on.

As of now, the entire audio folder is 20.5MB. I can reduce that by almost half just by reducing the sample rate, which will cut off a lot of higher frequencies, but since this is a text-based game and already very lo-fi sounding score I think the lower frequency range would work in favour of the aesthetic. I can also reduce a lot of the loop lengths as well.

I can get the audio to be at least under 10MB in total I know for sure, but uncertain how much further I could go with reducing loops, compression, etc.. Is there a certain amount of bandwidth you would be happy with for the audio that I could try and target?

**Comment by Continuities** [comment]
Basically, as small as possible. Last month, with audio enabled, ADR's
out-bound transfers totalled almost 700GB, which cost $80. The cutoff for
free usage is 50GB/month, which would be ideal, but is pretty unrealistic.
With more optimized delivery (only downloading audio when it's enabled, and
only loading sound as needed), smaller file formats, and alternative
hosting solutions (I'm looking into it), we might be able to get this thing
live again.

**Comment by orsi** [comment]
Fixed safari issue and also drastically reduced audio size!

- Total audio file assets reduced by over 75% (20.3MB to 5MB)!
- Removed preloading audio as this was an initial 10MB download (even more than all assets now!)

Pull request at https://github.com/doublespeakgames/adarkroom/pull/667 for review.
